# Generated by Django 3.2.16 on 2023-11-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0008_rename_image_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=40)),
                ('image', models.FileField(null=True, unique=True, upload_to='docs/')),
                ('date', models.DateField()),
            ],
        ),
    ]
