# Generated by Django 3.2.16 on 2023-11-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0011_massmedia_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massmedia',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='massmedia',
            name='color',
        ),
        migrations.AddField(
            model_name='massmedia',
            name='media',
            field=models.CharField(choices=[('instagram', 'INSTAGRAM'), ('site', 'SITE'), ('youtube', 'YOUTUBE'), ('vkontakte', 'VKONTAKTE')], default='instagram', max_length=9),
        ),
    ]
