# Generated by Django 3.2.16 on 2023-11-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0012_auto_20231122_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='massmedia',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='massmedia',
            name='text',
            field=models.CharField(max_length=70),
        ),
    ]
