# Generated by Django 3.2.16 on 2023-11-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0014_alter_massmedia_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmedia',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
