# Generated by Django 3.2.16 on 2023-11-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0015_alter_massmedia_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('text', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, unique=True, upload_to='docs/')),
            ],
        ),
        migrations.AlterField(
            model_name='massmedia',
            name='media',
            field=models.CharField(choices=[('instagram', 'INSTAGRAM'), ('site', 'SITE'), ('youtube', 'YOUTUBE'), ('vkontakte', 'VKONTAKTE')], default='site', max_length=9),
        ),
    ]
