# Generated by Django 3.2.16 on 2023-11-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0016_auto_20231124_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Magazine',
        ),
        migrations.AddField(
            model_name='massmedia',
            name='file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='massmedia',
            name='link',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
