# Generated by Django 3.2.16 on 2023-11-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0018_alter_massmedia_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='docs/')),
            ],
        ),
        migrations.AlterField(
            model_name='massmedia',
            name='media',
            field=models.CharField(choices=[('instagram', 'INSTAGRAM'), ('site', 'SITE'), ('youtube', 'YOUTUBE'), ('vkontakte', 'VKONTAKTE'), ('magazine', 'MAGAZINE')], default='site', max_length=9),
        ),
    ]
