# Generated by Django 3.2.16 on 2024-02-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0023_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.RemoveField(
            model_name='pdf_cart',
            name='title',
        ),
        migrations.AlterField(
            model_name='massmedia',
            name='date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='massmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='docx/', verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='massmedia',
            name='link',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='massmedia',
            name='media',
            field=models.CharField(choices=[('instagram', 'INSTAGRAM'), ('site', 'SITE'), ('youtube', 'YOUTUBE'), ('vkontakte', 'VKONTAKTE'), ('magazine', 'MAGAZINE')], default='site', max_length=9, verbose_name='Вид медии'),
        ),
        migrations.AlterField(
            model_name='massmedia',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='massmedia',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='pdf_cart',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/docx/', verbose_name='Путь к реквизитам'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(blank=True, max_length=80, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='conditions',
            field=models.CharField(max_length=200, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='requirements',
            field=models.CharField(max_length=300, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='responsibilities',
            field=models.CharField(max_length=200, verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary',
            field=models.CharField(max_length=30, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='workExperience',
            field=models.CharField(max_length=50, verbose_name='Опыт работы'),
        ),
    ]
