# Generated by Django 3.2.16 on 2024-02-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0024_auto_20240213_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDF_Cart',
            new_name='pdfCart',
        ),
    ]
