# Generated by Django 3.2.16 on 2024-02-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0025_rename_pdf_cart_pdfcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfcart',
            name='title',
            field=models.CharField(blank=True, max_length=80, unique=True, verbose_name='Реквизиты'),
        ),
    ]
